import { Router, type IRouter } from "express";
import healthRouter from "./health";
import stocksRouter from "./stocks";
import paymentRouter from "./payment";
import feedbackRouter from "./feedback";
import analyticsRouter from "./analytics";
import adminRouter from "./admin";
import devRouter from "./dev";
import watchlistRouter from "./watchlist";
import authRouter from "./auth";
import alertsRouter from "./alerts";
import pushTokensRouter from "./pushTokens";
import notificationsRouter from "./notifications";
import exportRouter from "./export";
import notifyRouter from "./notify";
import holdingsRouter from "./holdings";
import reportsRouter from "./reports";
import accountRouter from "./account";
import revenuecatRouter from "./revenuecat";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/stocks", stocksRouter);
router.use("/payment", paymentRouter);
router.use("/feedback", feedbackRouter);
router.use("/analytics", analyticsRouter);
router.use("/admin", adminRouter);
router.use("/dev", devRouter);
router.use("/watchlist", watchlistRouter);
router.use("/auth", authRouter);
router.use("/alerts", alertsRouter);
router.use("/push-tokens", pushTokensRouter);
router.use("/notifications", notificationsRouter);
router.use("/export", exportRouter);
router.use("/notify", notifyRouter);
router.use("/holdings", holdingsRouter);
router.use("/reports", reportsRouter);
router.use("/account", accountRouter);
router.use("/webhooks/revenuecat", revenuecatRouter);

export default router;
